### ISSUE TITLE
Sandbox should have the `glob` dependency?

### ISSUE THREAD

**Issue by karlhorky** [kentcdodds/learn-react#13]
Hi again @kentcdodds! 👋

Just took a look at these exercises as a potential recommendation for our students at @upleveled, and I noticed that [the sandbox](https://codesandbox.io/s/github/kentcdodds/learn-react) is currently failing with an error about a missing `glob` dependency:

<img src=https://user-images.githubusercontent.com/1935696/93670362-2ec8ae00-fa9b-11ea-8297-0a4acc6031cf.png width=450>

Not sure what dependency chain is causing this, but adding `glob` in the dependencies seems to have fixed it (see https://codesandbox.io/s/gallant-monad-x9izs).

If you think adding glob to the dependencies is an acceptable solution, then I could add this to the `package.json` in a pull request.

Cheers again for your work in the community!

**Comment by kentcdodds** [comment]
Sure, a pull request would be welcome

**Comment by karlhorky** [comment]
Cool, open at #14
