### ISSUE TITLE
Small typo in app.js

### ISSUE THREAD

**Issue by nathanhannig** [kentcdodds/learn-react#2]
Text on screen displays as:
`Please learn more by going tothe Learn React repo`

Here is the code
```
Please learn more by going to
<a href="https://github.com/kentcdodds/learn-react">
  the Learn React repo
</a>
```

As you are aware it just needs a `{' '}` on the end of the `to` so space is enforced.

**Comment by kentcdodds** [comment]
Thanks! Would you like to make a PR to fix that?!

**Comment by nathanhannig** [comment]
sure would!
