### ISSUE TITLE
Dependencies not Installing

### ISSUE THREAD

**Issue by Zaks0n** [kentcdodds/learn-react#7]
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\yallist-71e1f2d3\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\yallist-71e1f2d3\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\nice-try-50792a39\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\node-bin-setup-10e329b9\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\yallist-71e1f2d3\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\nice-try-50792a39\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\node-bin-setup-10e329b9\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\yallist-71e1f2d3\iterator.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\detect-port-alt-5f890c3b\bin\detect-port'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\nice-try-50792a39\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\mkdirp-a91b2897\examples\pow.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\yallist-71e1f2d3\yallist.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\nice-try-50792a39\CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\jsx-ast-utils-991f13ba\lib\values\expressions'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\_compare-by-length.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\fsevents-b3edc91f\node_modules\delegates\test\index.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\fsevents-b3edc91f\node_modules'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\bindCallback.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\bindCallback.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\bindNodeCallback.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\bindNodeCallback.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\combineLatest.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\combineLatest.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\concat.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\concat.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\ConnectableObservable.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\ConnectableObservable.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\defer.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\rxjs-0d2c9f7a\_esm5\internal\observable\defer.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\core-js-d6ad0093\library\fn\promise\finally.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\core-js-d6ad0093\library\fn\promise\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\core-js-d6ad0093\library\fn\promise\try.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\filter\implement.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\filter\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\filter\is-implemented.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\filter\shim.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\splice\implement.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\splice\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\splice\is-implemented.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\splice\shim.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\array\#\uniq.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\test\string\#'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\test'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\test\string\#\repeat\implement.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\test\string\#\repeat\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\test\string\#\repeat\is-implemented.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Zaks0n\Desktop\learn-react-master\node_modules\.staging\es5-ext-a53bab23\test\string\#\repeat\shim.js'
npm ERR! Unexpected end of JSON input while parsing near '...-eslint":"^8.2.5","ba'

**Comment by kentcdodds** [comment]
Sorry, I don't know what's wrong. It works fine on my machine. There must be a problem on your computer :-/
